---
title: "Iris Machine Learning"
output: html_document
---

```{r}
library(ggplot2)
library(plyr)
library(datasets)
library(ggvis)
library(class)
library(gmodels)


# load iris data set
data("iris")
```

klkjl
```{r}
iris %>% ggvis(~Sepal.Length, ~Sepal.Width, fill = ~Species) %>% layer_points()
```

```{r}
iris %>% ggvis(~Petal.Length, ~Petal.Width, fill = ~Species) %>% layer_points()
```

```{r}
head(iris)
```

```{r}

str(iris)

```

```{r}
table(iris$Species)
```

```{r}
round(prop.table(table(iris$Species)) * 100, digits = 1)
```

```{r}
summary(iris)
```

```{r}
normalize <- function(x) {
num <- x - min(x)
denom <- max(x) - min(x)
return (num/denom)
}
```

YourNormalizedDataSet <- as.data.frame(lapply(YourDataSet, normalize))

```{r}
iris_norm <- as.data.frame(lapply(iris[1:4], normalize))
```

```{r}
summary(iris_norm)
```

```{r}
set.seed(1234)
```

```{r}
ind <- sample(2, nrow(iris), replace=TRUE, prob=c(0.67, 0.33))
```

```{r}
iris.training <- iris[ind==1, 1:4]
iris.test <- iris[ind==2, 1:4]
```

```{r}
iris.trainLabels <- iris[ind==1, 5]
iris.testLabels <- iris[ind==2, 5]
```

```{r}
iris_pred <- knn(train = iris.training, test = iris.test, cl = iris.trainLabels, k=3)
```

```{r}
iris_pred
```

```{r}
CrossTable(x = iris.testLabels, y = iris_pred, prop.chisq=FALSE)
```

```{r}

```

```{r}

```

