install.packages("xlsx")
install.packages("dplyr")
install.packages("tidyr")
install.packages("stringr")
install.packages("lubridate")
install.packages("ggvis")
install.packages("googleVis")
install.packages("car")
install.packages("randomForest")
install.packages("caret")
install.packages("shiny")
install.packages("feather")
install.packages("zoo")
install.packages("jsonlite")
install.packages("XML")
install.packages("ggplot2")

# library("xlsx")
library("dplyr")
library("tidyr")
# library("stringr")
# library("lubridate")
# library("ggvis")
library("googleVis")
# library("car")
library("randomForest")
# library("caret")
library("shiny")
library("feather")
# library("zoo")
# library("jsonlite")
# library("XML")
library("ggplot2")